name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨执行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'youremail@example.com'

      - name: Fetch Upstream
        run: git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git

      - name: Merge Upstream
        run: git fetch upstream && git merge upstream/main

      - name: Push Changes
        run: git push origin main
        env:
          PAT: ${{ secrets.PAT }}
