name: Sync with upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
